### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by dzikoysk** [panda-lang/panda#1]
Hello @wujunze, 

I sent you an email, but I think it could be marked as spam. The topic is connected with your organization and it's really important for me. Could you check your spam looking for the message from `dzikoysk@dzikoysk.net`?

Thanks for your time ❤️

**Comment by dzikoysk** [comment]
@wujunze I've just also sent an email through gmail using `dzikoysk@gmail.com` address. I think it might be more reliable way of contact.

**Comment by wujunze** [comment]
I have replied to your email. Thank you @dzikoysk
