### ISSUE TITLE
Does it works?

### ISSUE THREAD

**Issue by chailyode** [panda-lang/panda#383]
Hi, I'm pretty impressed by the complexity of the project, does it works at this moment?

**Comment by dzikoysk** [comment]
Hey @chailyode, I've almost finished the first milestone - [release alpha](https://github.com/panda-lang/panda/milestone/1). A lot of things already work (all listed here: [examples](https://github.com/panda-lang/panda/tree/master/examples)) , but API is just not stable :)

**Comment by chailyode** [comment]
Oh, awesome, can't wait and also thanks for pandomium 😌
