### ISSUE TITLE
Panda Framework?

### ISSUE THREAD

**Issue by qaquaore** [panda-lang/panda#563]
I'm looking for some kind of utility framework to create own DSL language on JVM. I see that "build your own language on top of the Panda Framework.". What do you.mean by that and is it a stable solution?

**Comment by dzikoysk** [comment]
Hey, thanks for question :)

Well, as you can see, Panda is at this moment in alpha phase. What does it mean? I've made an article about it, just take a look at panda-lang blog: https://panda-lang.org/news/releases-roadmap

The alpha phase goal is to make API stable and user-friendly, so people as you - interested in Panda Framework - should wait for the bete realease to get all that stuff. It why I can't recommend it now, but stay tuned for the future releases.

**Comment by qaquaore** [comment]
Oh, ok , thanks :+1:
